@startuml
title Super Admin Role Management

|Super Administrator|
start
:Log into system;
:Open User Management;
:Select target user;
:Select new role:
-Super Admin
-Facility Admin
-Inventory Admin
-Marketplace Admin
-User;

|System|
if (Valid role change?) then (Yes)
    :Update target user's role in database;

    fork
      :Record action in access log;
    fork again
      :Show success message;
    end fork

  else (No)
  fork
    :Show error message;
    fork again;
    :Record action in access log;
    end fork
  endif


|Affected User|
:Automatic Logout from system;

|System|
:Load current role on login;
:Apply updated permissions;
:Display interface and modules\naccording to their new role;

end
@enduml