@startuml
left to right direction
skinparam packageStyle rectangle

actor "Facility Administrator" as FacilityAdmin

rectangle MAIKINE {

  usecase "Log-In" as UC_Login
  usecase "Log-Out" as UC_Logout
  usecase "Access\noperational\ncost report" as UC_OperationalCost
  usecase "Download\nfacility operational cost as CSV" as UC_DownloadCost
  usecase "Add facility\nlending event" as UC_AddEvent
  usecase "Delete\nfacility lending\nevent" as UC_DeleteEvent
  usecase "Search events" as UC_Search
  usecase "Filter events" as UC_Filter
}

FacilityAdmin --> UC_Login
FacilityAdmin --> UC_Logout

UC_Login <.. UC_OperationalCost : <<extend>>

UC_OperationalCost <.. UC_DownloadCost : <<extend>>
UC_OperationalCost <.. UC_AddEvent : <<extend>>
UC_OperationalCost <.. UC_DeleteEvent : <<extend>>
UC_OperationalCost <.. UC_Search : <<extend>>
UC_OperationalCost <.. UC_Filter : <<extend>>

note left of UC_Logout
Available from any
authenticated state
end note

@enduml