@startuml
left to right direction
skinparam packageStyle rectangle

actor "Inventory Administrator" as InventoryAdmin

rectangle MAIKINE {

  usecase "Login" as UC_Login
  usecase "Browse\nInventory\nManagement" as UC_InventoryMgmt
  usecase "Add\ninventory" as UC_AddInventory
  usecase "Update\nInventory" as UC_UpdateInventory
  usecase "Remove\nfrom inventory" as UC_RemoveInventory
  usecase "Approve\nrequests" as UC_ApproveRequests
  usecase "Deny\nrequests" as UC_DenyRequests
  usecase "View invetory statistics" as UC_ViewStatisitcs
  usecase "View active\nborrowers" as UC_ViewBorrowers
  usecase "Browse\nDepartment\nInventory" as UC_DepLending
  usecase "Ban user" as UC_BanUser
  usecase "Search user" as UC_SearchUser
  usecase "View Inventory" as UC_View
  usecase "View requests" as UC_ViewRequest
  usecase "Search inventory" as UC_Search
  usecase "Filter inventory" as UC_Filter
  usecase "Log out" as UC_Logout

  note right of (UC_Logout)
  Log out is an extend of all other views and usecases
  end note

  note right of (UC_DenyRequests)
  If the user wishes to request an equipment for longer than one day 
  the InventoryAdmin my deny the request
  end note

  note right of (UC_ApproveRequests)
  If the user wishes to request an equipment for longer than one day 
  the InventoryAdmin my approve the request..
  end note


}

InventoryAdmin -- UC_Login

UC_Login <.. UC_Logout : <<extend>>
UC_Login <.. UC_InventoryMgmt : <<extend>>
UC_Login <.. UC_DepLending : <<extend>>
UC_Login <.. UC_SearchUser : <<extend>>

UC_InventoryMgmt <.. UC_AddInventory : <<extend>>
UC_InventoryMgmt <.. UC_RemoveInventory : <<extend>>
UC_InventoryMgmt <.. UC_ApproveRequests : <<extend>>
UC_InventoryMgmt <.. UC_DenyRequests : <<extend>>
UC_InventoryMgmt <.. UC_ViewBorrowers : <<extend>>
UC_InventoryMgmt <.. UC_View: <<extend>>
UC_InventoryMgmt <.. UC_ViewRequest: <<extend>>
UC_InventoryMgmt <.. UC_ViewStatisitcs : <<extend>>

UC_AddInventory ..> UC_UpdateInventory : <<include>>
UC_RemoveInventory ..> UC_UpdateInventory : <<include>>
UC_ApproveRequests ..> UC_RemoveInventory : <<include>>

UC_SearchUser <.. UC_BanUser : <<extend>>

UC_DepLending <.. UC_Search : <<extend>>
UC_DepLending <.. UC_Filter :: <<extend>>


@enduml