@startuml
left to right direction
skinparam packageStyle rectangle

actor "Marketplace Administrator" as MarketplaceAdmin

rectangle MAIKINE {

  usecase "Log-In" as UC_Login
  usecase "Log-Out" as UC_Logout
  usecase "Access\nMarketplace" as UC_Marketplace
  usecase "Browse\nmarketplace" as UC_Browse
  usecase "Search users" as UC_SearchUsers
  usecase "Add listing" as UC_AddListing
  usecase "Delete listing" as UC_DeleteListing
  usecase "Access\nMarketplace\nManagement" as UC_MarketMgmt
  usecase "Review\nreported\naccounts" as UC_ReviewReports
  usecase "Delete user\nlisting" as UC_DeleteUserListing
  usecase "Ban user" as UC_BanUser
  usecase "View posts" as UC_View
  usecase "Review flagged report" as UC_ViewFlagged
  usecase "View user profile" as UC_ViewProfile
  usecase "Dismiss report" as UC_Dismiss
  usecase "Resolve report" as UC_Resolve
  usecase "View reviews" as UC_ViewReview
  usecase "Filter posts" as UC_Filter
  usecase "Report post" as UC_Report
  usecase "Chat with user" as UC_Chat

}

MarketplaceAdmin --> UC_Login
MarketplaceAdmin --> UC_Logout

UC_Login ..> UC_Marketplace : <<include>>
UC_Login ..> UC_MarketMgmt : <<include>>

UC_Marketplace ..> UC_Browse : <<include>>
UC_Marketplace ..> UC_SearchUsers : <<include>>
UC_Marketplace ..> UC_AddListing : <<include>>
UC_Marketplace ..> UC_DeleteListing : <<include>>
UC_Marketplace ..> UC_Filter : <<include>>
UC_Marketplace ..> UC_Report : <<include>>
UC_Marketplace ..> UC_Chat : <<include>>

UC_MarketMgmt ..> UC_ReviewReports : <<include>>
UC_MarketMgmt ..> UC_DeleteUserListing : <<include>>
UC_MarketMgmt ..> UC_BanUser : <<include>>
UC_MarketMgmt ..> UC_View : <<include>>
UC_MarketMgmt ..> UC_ViewProfile: <<include>>
UC_MarketMgmt ..> UC_ViewFlagged: <<include>>
UC_MarketMgmt ..> UC_Dismiss: <<include>>
UC_MarketMgmt ..> UC_Resolve: <<include>>
UC_MarketMgmt ..> UC_ViewReview: <<include>>

@enduml