@startuml
left to right direction
skinparam packageStyle rectangle

actor "Marketplace Administrator" as MarketplaceAdmin

rectangle MAIKINE {

  usecase "Log-In" as UC_Login
  usecase "Log-Out" as UC_Logout

  usecase "Browse\nmarketplace" as UC_Browse
  usecase "Search users" as UC_SearchUsers
  usecase "Add user listing" as UC_AddListing
  usecase "Delete user\nlisting" as UC_DeleteUserListing
  usecase "Chat with user" as UC_Chat
  usecase "Report a post" as UC_Report

  usecase "Review\nreported\naccounts" as UC_ReviewAccounts
  usecase "Ban user" as UC_BanUser

  usecase "View posts" as UC_View
  usecase "Filter posts" as UC_Filter
  usecase "Review flagged report" as UC_ViewFlagged
  usecase "Resolve report" as UC_Resolve
  usecase "Dismiss report" as UC_Dismiss
  usecase "View user profile" as UC_ViewProfile
  usecase "View reviews" as UC_ViewReview
}

MarketplaceAdmin --> UC_Login
MarketplaceAdmin --> UC_Logout

UC_Login <.. UC_Browse : <<extend>>
UC_Login <.. UC_SearchUsers : <<extend>>
UC_Login <.. UC_AddListing : <<extend>>
UC_Login <.. UC_Chat : <<extend>>
UC_Login <.. UC_Report : <<extend>>
UC_Login <.. UC_BanUser : <<extend>>

UC_Login <.. UC_View : <<extend>>
UC_Login <.. UC_ReviewAccounts : <<extend>>
UC_Login <.. UC_ViewFlagged : <<extend>>
UC_Login <.. UC_ViewProfile : <<extend>>
UC_Login <.. UC_DeleteUserListing : <<extend>>

UC_Filter ..> UC_View : <<extend>>
UC_ViewFlagged ..> UC_View : <<extend>>

UC_Resolve ..> UC_ViewFlagged : <<extend>>
UC_Dismiss ..> UC_ViewFlagged : <<extend>>

UC_ViewReview ..> UC_ViewProfile : <<extend>>

UC_View -[hidden]-> UC_Filter
UC_View -[hidden]-> UC_ViewFlagged
UC_ViewFlagged -[hidden]-> UC_Resolve
UC_Resolve -[hidden]-> UC_Dismiss
UC_ViewFlagged -[hidden]-> UC_ViewProfile
UC_ViewProfile -[hidden]-> UC_ViewReview

note left of UC_Logout
Available from any
authenticated state
end note

@enduml