@startuml
left to right direction
skinparam packageStyle rectangle

actor User
actor "Inventory Administrator" as InventoryAdmin
actor "Marketplace Administrator" as MarketplaceAdmin
actor "Facility Administrator" as FacilityAdmin
actor "Super Administrator" as SiteAdmin

SiteAdmin <|-- User
SiteAdmin <|-- InventoryAdmin
SiteAdmin <|-- MarketplaceAdmin
SiteAdmin <|-- FacilityAdmin

rectangle MAIKINE {

  
    usecase "Login" as UC_Login
    usecase "Log out" as UC_Logout
    usecase "Restore user account" as UC_RestoreUser
    usecase "Ban user access" as UC_BanUser
    usecase "View access logs" as UC_ViewLogs
    usecase "Manage user roles" as UC_ManageRoles
    usecase "Edit operational costs" as UC_EditCost
  
    
    usecase "Filter access logs" as UC_FilterLogs
    usecase "Search access logs" as UC_SearchLogs
    usecase "Download access logs CSV" as UC_DownloadLogs

  
    usecase "View users" as UC_ViewUsers
    usecase "Assign role" as UC_AssignRole
    usecase "Promote user role" as UC_PromoteRole
    usecase "Demote user role" as UC_DemoteRole
    usecase "Modify role" as UC_RemoveRole

    note bottom of (UC_Logout)
  Log out is an extend of all other views and usecases
  end note

   note bottom of (UC_EditCost)
   This use case assumes the Super Administrator has
   entered the facility operational cost report page.
   end note
  
}

SiteAdmin -- UC_Login
UC_Login <.. UC_Logout :<<extend>>
UC_Login <.. UC_ViewLogs : <<extend>>
UC_Login <.. UC_ManageRoles : <<extend>>
UC_Login <.. UC_EditCost : <<extend>>



UC_ViewLogs <.. UC_SearchLogs : <<extend>>
UC_ViewLogs <.. UC_DownloadLogs : <<extend>>
UC_ViewLogs <.. UC_FilterLogs : <<extend>>


UC_ManageRoles <.. UC_ViewUsers : <<extend>>
UC_ManageRoles <.. UC_AssignRole : <<extend>>
UC_ManageRoles <.. UC_PromoteRole : <<extend>>
UC_ManageRoles <.. UC_DemoteRole : <<extend>>
UC_ManageRoles <.. UC_RemoveRole : <<extend>>
UC_ManageRoles <.. UC_BanUser : <<extend>>
UC_ManageRoles <.. UC_RestoreUser : <<extend>>



@enduml