@startuml
left to right direction
skinparam packageStyle rectangle

actor User

rectangle MAIKINE {

  usecase "Login" as UC_Login
  usecase "Browse Marketplace" as UC_BrowseMP
  usecase "Read/view Contact Information" as UC_ReadContact
  usecase "Search for equipment" as UC_Search
  usecase "Filter equipment by sport" as UC_Filter
  usecase "View a post" as UC_Listing
  usecase "Chat with seller" as UC_Chat
  usecase "Rate an account" as UC_Rate
  usecase "Report an account" as UC_Report
  usecase "Receive an email notification after a chat\n has been left unread for 15 minutes" as UC_EmailChat
  usecase "Receive pending status" as UC_Pending
  usecase "Search/ filter users" as UC_SearchUser
  usecase "Post equipment for sale" as UC_List
  usecase "Delete own post" as UC_DeleteList
  usecase "Browse Department Kinventory" as UC_BrowseIN
  usecase "Browse User Profile" as UC_BrowsePF
  usecase "Search for equipment" as UC_EquipSearch
  usecase "Filter by equipment" as UC_EquipFilter
  usecase "View own post" as UC_View
  usecase "View own chats" as UC_ViewChat
  usecase "View own borrow requests" as UC_BorrowRequest
  usecase "View own reviews/ratings" as UC_Review
  usecase "Log out" as UC_Logout
  usecase "Request sport equipment for lending" as UC_Request
  usecase "Receive equipment approval/denial email" as UC_EmailResponse

  note right of (UC_Logout)
  Log out is an extend of all other views and usecases
  end note
}

User -- UC_Login
UC_Login <.. UC_BrowseIN : <<extend>>
UC_Login <.. UC_ReadContact : <<extend>>
UC_Login <.. UC_Logout  : <<extend>>
UC_Login <.. UC_BrowseMP : <<extend>>
UC_Login <.. UC_BrowsePF : <<extend>>
UC_Login <.. UC_SearchUser:<<extend>>


UC_BrowsePF <.. UC_DeleteList : <<extend>>
UC_BrowsePF <.. UC_View : <<extend>>
UC_BrowsePF <.. UC_ViewChat : <<extend>>
UC_BrowsePF <.. UC_BorrowRequest : <<extend>>
UC_BrowsePF <.. UC_Review : <<extend>>

UC_BrowseMP <.. UC_List : <<extend>>
UC_Search ..> UC_BrowseMP : <<extend>>
UC_Filter ..> UC_BrowseMP : <<extend>>
UC_Listing ..> UC_BrowseMP : <<extend>>

UC_Chat ..> UC_Listing : <<extend>>
UC_EmailChat ..> UC_Chat : <<extend>>
UC_Rate ..> UC_Listing : <<extend>>
UC_Report ..> UC_Listing : <<extend>>

UC_EquipSearch ..> UC_BrowseIN : <<extend>>
UC_EquipFilter ..> UC_BrowseIN : <<extend>>
UC_Request <.. UC_Pending: <<extend>>
UC_EmailResponse ..> UC_Request : <<extend>>
UC_BrowseIN <.. UC_Request : <<extend>>


UC_BrowseMP -[hidden]-> UC_Search
UC_Search -[hidden]-> UC_Filter
UC_Filter -[hidden]-> UC_Listing
UC_Listing -[hidden]-> UC_Chat
UC_Chat -[hidden]-> UC_Rate
UC_Rate -[hidden]-> UC_Report
UC_Report -[hidden]-> UC_EmailChat

UC_BrowseIN -[hidden]-> UC_EquipSearch
UC_EquipSearch -[hidden]-> UC_EquipFilter
UC_EquipFilter -[hidden]-> UC_Request
UC_Request -[hidden]-> UC_EmailResponse

@enduml